services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: oeminventory
      POSTGRES_PASSWORD: oeminventory_dev_only
      POSTGRES_DB: oeminventory
    ports:
      - '5432:5432'
    volumes:
      - oeminventory_postgres_data:/var/lib/postgresql/data

volumes:
  oeminventory_postgres_data:
